# Generated by Django 5.2.12 on 2026-03-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning (up to 9:30 AM)'), ('afternoon', 'Afternoon (up to 2:15 PM)')], default='morning', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'session')},
        ),
    ]
